version: '3.1'

services: 
    wordpress:
        image: wordpress:latest
        container_name: siteWP
        ports: 
            - 8183:80
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ODUser
            WORDPRESS_DB_PASSWORD: ODPass
            WORDPRESS_DB_NAME: ODDb
        volumes: 
            - ./wordpress/:/var/www/html
    db:
        image: mysql:5.7
        environment: 
            MYSQL_DATABASE: ODDb
            MYSQL_USER: ODUser
            MYSQL_PASSWORD: ODPass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes: 
            - db:/var/lib/mysql
volumes: 
    db:
            